### ISSUE TITLE
403 after first session timeout

### ISSUE THREAD

**Issue by epPDI** [rgommezz/react-native-chatgpt#10]
After login, all is working until the session expires. At that point, the code should call `reloadWebView` due to 403 response, but instead the 403 response is seemingly doing nothing.

**Comment by rgommezz** [comment]
It should refresh the session every time the app gets foregrounded: https://github.com/rgommezz/react-native-chatgpt/blob/44c6518ac6921bc2697b6a85c8e0e215338d17a2/src/components/ModalWebView.tsx#L96-L104

I can't really help you if you don't provide further details.
