### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by ThamirizDiniz** [rgommezz/react-native-chatgpt#12]
how to force a logout and go back to the beginning for a new login, I looked in the files but didn't find any function, currently I'm trying to clean or delete the token but without success.

**Comment by marquezjorge** [comment]
any luck?

**Comment by ThamirizDiniz** [comment]
I made a function to destroy the TOKEN_ACCESS_KEY and reload the App.tsx

=\

**Comment by illusion77** [comment]
> I made a function to destroy the TOKEN_ACCESS_KEY and reload the App.tsx
> 
> =\

I use flush() to delete the key TOKEN_ACCESS_KEY, but it will still retrieve the key after I refresh the app. Could you provide some of your modified code? Thx!
