### ISSUE TITLE
Unable to resolve "@babel/runtime/helpers/interopRequireDefault" from "..\src\index.tsx"

### ISSUE THREAD

**Issue by john012343210** [rgommezz/react-native-chatgpt#6]
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Android Bundling failed 550ms
Unable to resolve "@babel/runtime/helpers/interopRequireDefault" from "..\src\index.tsx"

**Comment by ox-vishal** [comment]
Facing same issue

**Comment by rgommezz** [comment]
I was able to run the Snack Expo example on both Android emulator and my own device. The local Example project also bundles correctly. Please provide more details like environment, version, etc.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4982414/231607126-e2a4143b-0bad-4b99-9a31-a533cf1388e7.png">
